version: "3.8"
services:
  postgis:
    image: postgis/postgis
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo

volumes:
  pgdata: {}
